# Generated by Django 2.1.3 on 2018-11-19 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0004_auto_20181117_1859'),
    ]

    operations = [
        migrations.DeleteModel(
            name='reserva',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.Bicicleta'),
        ),
    ]
