# Generated by Django 2.1.3 on 2018-11-19 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_auto_20181119_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='bicicleta',
            name='modelo',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
