# Generated by Django 2.1.3 on 2018-11-18 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0006_auto_20181117_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileadmin',
            name='user',
        ),
        migrations.DeleteModel(
            name='ProfileAdmin',
        ),
    ]
