# Generated by Django 2.1.3 on 2018-11-18 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_auto_20181117_0310'),
        ('authenticate', '0007_auto_20181118_0314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bicicletas',
        ),
        migrations.AddField(
            model_name='profile',
            name='bicicletas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.bicicleta'),
        ),
    ]
